# Generated by Django 4.2.2 on 2023-11-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labouruser',
            name='skills',
            field=models.CharField(default='No skills', max_length=50),
        ),
        migrations.AlterField(
            model_name='labouruser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
