# Generated by Django 4.2.2 on 2023-11-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_labouruser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labouruser',
            name='excperience',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='labouruser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
