# Generated by Django 4.2.2 on 2023-11-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_labouruser_excperience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labouruser',
            name='excperience',
            field=models.IntegerField(default=0),
        ),
    ]
