# Generated by Django 4.2.2 on 2023-11-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_labouruser_excperience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labouruser',
            name='excperience',
        ),
    ]
