# Generated by Django 4.2.2 on 2023-11-09 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_labouruser_excperience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labouruser',
            name='excperience',
        ),
    ]
