# Generated by Django 4.2.2 on 2023-11-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_productimage_serviceimage_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='labouruser',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
