# Generated by Django 4.2.2 on 2023-11-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_labouruser_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labouruser',
            name='mobile',
            field=models.PositiveIntegerField(),
        ),
    ]
